# Generated by Django 5.2.6 on 2025-09-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
    ]
