# Generated by Django 5.2.6 on 2025-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0003_alter_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
