# Generated by Django 5.2.6 on 2025-09-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_on_post', 'Comment on your post'), ('like_on_post', 'Like on your post'), ('like_on_comment', 'Like on your comment'), ('friend_request', 'New friend request'), ('friend_accepted', 'Friend request accepted'), ('new_message', 'New message')], max_length=32),
        ),
    ]
